# Generated by Django 4.2 on 2023-04-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tow_factor',
            field=models.BooleanField(default=False),
        ),
    ]
